// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://xyzfansfddzndxctjdfa.supabase.co';
const SUPABASE_PUBLISHABLE_KEY =
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh5emZhbnNmZGR6bmR4Y3RqZGZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY2OTcxOTcsImV4cCI6MjA1MjI3MzE5N30.kQTw8lG6f9PppnbbRin5l1zWTnsHHtzXgOxDgL3I7jY';

export const supabase = createClient<Database>(
    SUPABASE_URL,
    SUPABASE_PUBLISHABLE_KEY
);
